let sugestoes = [
    "Celular",
    "Ipad",
    "Samsung",
    "Iphone",
    "Motorola",
    "Fone",
    "Power Bank",
    "Pelicula",
    "Capinha",
    "Cassio Egipcio",
    "Xiaomi",
    "Poco",
    "Tablet",
    "Smart",
    "SmartWatch",
    "Smart band",
    "Caixa de som",
    "Jbl",
    "Carregador",
    "Cabo USB-C",
    "Cabo lightning",
    "Cabo para Iphone",
    "Carregador por indução",
    "Carregador sem fio",
    "Fone sem fio",
    "Fone Bluetooth",
    "Airpods",
    "S23 Ultra",
    "S23",
    "S22",
    "S20FE",
    "S24 Ultra",
    "Iphone 12",
    "Iphone 12 pro",
    "Iphone 12 pro max",
    "Iphone 11",
    "Iphone 11 pro",
    "Iphone 11 pro max",
    "Iphone 13",
    "Iphone 13 pro",
    "Iphone 13 pro max",
    "Iphone 14",
    "Iphone 14 pro",
    "Iphone 14 pro max",
    "Iphone 15",
    "Iphone 15 pro",
    "Iphone 15 pro max",
    "J5 Prime",
    "LG K10",
    "Rog Phone",
    "Poco x4 pro",
    "Poco x5",
    "Carregador veicular",
    "Carregador de carro",
    "Microfone",
    "Mãe do David"
]